export const data = [
  {
    id: 1,
    projectTitle: "Birthday Reminder",
    img: "assets/birthday-reminder.jpg",
    liveUrl: "https://simple-birthday-reminder-ys.netlify.app",
  },
  {
    id: 2,
    projectTitle: "Tours",
    img: "assets/tours.jpg",
    liveUrl: "https://simple-tours-ys.netlify.app",
  },
  {
    id: 3,
    projectTitle: "Reviews",
    img: "assets/reviews.jpg",
    liveUrl: "https://simple-reviews-ys.netlify.app",
  },
  {
    id: 4,
    projectTitle: "Accordion",
    img: "assets/accordion.jpg",
    liveUrl: "https://simple-accordion-ys.netlify.app",
  },
  {
    id: 5,
    projectTitle: "Menu",
    img: "assets/menu.jpg",
    liveUrl: "https://simple-menu-ys.netlify.app",
  },
  {
    id: 6,
    projectTitle: "Tabs",
    img: "assets/tabs.jpg",
    liveUrl: "https://simple-tabs-ys.netlify.app",
  },
  {
    id: 7,
    projectTitle: "Slider",
    img: "assets/slider.jpg",
    liveUrl: "https://simple-slider-ys.netlify.app",
  },
  {
    id: 8,
    projectTitle: "Lorem Ipsum",
    img: "assets/lorem-ipsum.jpg",
    liveUrl: "https://simple-lorem-ipsum-ys.netlify.app",
  },
  {
    id: 9,
    projectTitle: "Grocery Bud",
    img: "assets/grocery-bud.jpg",
    liveUrl: "https://simple-grocery-bud-ys.netlify.app",
  },
  {
    id: 10,
    projectTitle: "Navbar",
    img: "assets/navbar.jpg",
    liveUrl: "https://simple-navbar-ys.netlify.app",
  },
  {
    id: 11,
    projectTitle: "Slider And Modal",
    img: "assets/slider-and-modal.jpg",
    liveUrl: "https://simple-sidebar-modal-ys.netlify.app",
  },
  {
    id: 12,
    projectTitle: "Cart",
    img: "assets/cart.jpg",
    liveUrl: "https://simple-cart-ys.netlify.app",
  },
  {
    id: 13,
    projectTitle: "Cocktails",
    img: "assets/cocktails.jpg",
    liveUrl: "https://simple-cocktail-ys.netlify.app",
  },
];
