export const data = [
  {
    id: 1,
    projectTitle: "Birthday Reminder",
    img: "assets/birthday-reminder.jpg",
    liveUrl: "",
    githubUrl: "",
  },
  {
    id: 2,
    projectTitle: "Tours",
    img: "assets/tours.jpg",
    liveUrl: "",
    githubUrl: "",
  },
  {
    id: 3,
    projectTitle: "Reviews",
    img: "assets/reviews.jpg",
    liveUrl: "",
    githubUrl: "",
  },
  {
    id: 4,
    projectTitle: "Accordion",
    img: "assets/accordion.jpg",
    liveUrl: "",
    githubUrl: "",
  },
  {
    id: 5,
    projectTitle: "Menu",
    img: "assets/menu.jpg",
    liveUrl: "",
    githubUrl: "",
  },
  {
    id: 6,
    projectTitle: "Tabs",
    img: "assets/tabs.jpg",
    liveUrl: "",
    githubUrl: "",
  },
  {
    id: 7,
    projectTitle: "Slider",
    img: "assets/slider.jpg",
    liveUrl: "",
    githubUrl: "",
  },
  {
    id: 8,
    projectTitle: "Lorem Ipsum",
    img: "assets/lorem-ipsum.jpg",
    liveUrl: "",
    githubUrl: "",
  },
  {
    id: 9,
    projectTitle: "Grocery Bud",
    img: "assets/grocery-bud.jpg",
    liveUrl: "",
    githubUrl: "",
  },
  {
    id: 10,
    projectTitle: "Navbar",
    img: "assets/navbar.jpg",
    liveUrl: "",
    githubUrl: "",
  },
  {
    id: 11,
    projectTitle: "Slider And Modal",
    img: "assets/slider-and-modal.jpg",
    liveUrl: "",
    githubUrl: "",
  },
  {
    id: 12,
    projectTitle: "Cart",
    img: "assets/cart.jpg",
    liveUrl: "",
    githubUrl: "",
  },
  {
    id: 13,
    projectTitle: "Cocktails",
    img: "assets/cocktails.jpg",
    liveUrl: "",
    githubUrl: "",
  },
];
